---
name: Test actions
    
on:
    workflow_dispatch:
    push:
        branches:
            - main 
jobs:
    test:
        runs-on: ubuntu-latest
        name: just test debug action
        steps:
            - name: Checkout
                uses: actions/checkout@v4
                with:
                fetch-depth: 1
            - uses: ./
